import { BasicInfo, ProfileId, profileIds } from './types'

export { profileIds }

export const mockDataByProfile: Record<ProfileId, BasicInfo> = {
  EMPLOYED: {
    name: 'Carlos Andrés',
    lastName: 'Rodríguez',
    email: 'carlos.rodriguez@empresa.com',
    phone: '+57 310 555 1234',
    birthDate: '1988-03-12',
    birthPlace: 'Bogotá',
    documentType: 'CC',
    documentNumber: '1012345678',
    gender: 'MALE',
    maritalStatus: 'MARRIED',
    profession: 'Analista financiero',
    monthlyIncome: '5500000',
  },
  INDEPENDENT: {
    name: 'María Fernanda',
    lastName: 'López',
    email: 'mf.lopez@freelance.com',
    phone: '+57 315 555 5678',
    birthDate: '1992-07-22',
    birthPlace: 'Medellín',
    documentType: 'CC',
    documentNumber: '1023456789',
    gender: 'FEMALE',
    maritalStatus: 'SINGLE',
    profession: 'Diseñadora gráfica',
    monthlyIncome: '6200000',
  },
  RETIRED: {
    name: 'Jorge Alberto',
    lastName: 'Martínez',
    email: 'jorge.martinez@gmail.com',
    phone: '+57 320 555 9012',
    birthDate: '1958-11-08',
    birthPlace: 'Cali',
    documentType: 'CC',
    documentNumber: '1034567890',
    gender: 'MALE',
    maritalStatus: 'WIDOWED',
    profession: 'Pensionado',
    monthlyIncome: '4800000',
  },
  ENTREPRENEUR: {
    name: 'Ana Patricia',
    lastName: 'Gómez',
    email: 'ana.gomez@miempresa.com',
    phone: '+57 312 555 3456',
    birthDate: '1985-05-20',
    birthPlace: 'Barranquilla',
    documentType: 'CC',
    documentNumber: '900123456',
    gender: 'FEMALE',
    maritalStatus: 'MARRIED',
    profession: 'Empresaria',
    monthlyIncome: '8500000',
  },
  INVESTOR: {
    name: 'Roberto Carlos',
    lastName: 'Sánchez',
    email: 'roberto.sanchez@inversiones.com',
    phone: '+57 318 555 7890',
    birthDate: '1979-01-15',
    birthPlace: 'Bucaramanga',
    documentType: 'CC',
    documentNumber: '987654321',
    gender: 'MALE',
    maritalStatus: 'DIVORCED',
    profession: 'Inversionista',
    monthlyIncome: '12000000',
  },
  STUDENT: {
    name: 'Laura Valentina',
    lastName: 'Moreno',
    email: 'laura.moreno@universidad.edu.co',
    phone: '+57 314 555 2345',
    birthDate: '2001-09-14',
    birthPlace: 'Manizales',
    documentType: 'TI',
    documentNumber: '456789123',
    gender: 'FEMALE',
    maritalStatus: 'SINGLE',
    profession: 'Estudiante',
    monthlyIncome: '2500000',
  },
  FOREIGN: {
    name: 'Michael',
    lastName: 'Anderson',
    email: 'michael.anderson@company.com',
    phone: '+57 316 555 6789',
    birthDate: '1986-04-25',
    birthPlace: 'Austin',
    documentType: 'PASSPORT',
    documentNumber: 'AA1234567',
    gender: 'MALE',
    maritalStatus: 'COMMON_LAW',
    profession: 'Consultor',
    monthlyIncome: '7500000',
  },
  NOMAD: {
    name: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@remote.io',
    phone: '+57 319 555 0123',
    birthDate: '1990-12-10',
    birthPlace: 'Toronto',
    documentType: 'PASSPORT',
    documentNumber: 'P12345678',
    gender: 'FEMALE',
    maritalStatus: 'SINGLE',
    profession: 'Product manager',
    monthlyIncome: '9500000',
  },
  UNEMPLOYED: {
    name: 'Diego',
    lastName: 'Ramírez',
    email: 'diego.ramirez@gmail.com',
    phone: '+57 311 555 1212',
    birthDate: '1994-06-18',
    birthPlace: 'Pereira',
    documentType: 'CC',
    documentNumber: '123123123',
    gender: 'MALE',
    maritalStatus: 'SINGLE',
    profession: 'Sin ocupación',
    monthlyIncome: '0',
  },
}
