import { ProfileConfig, ProfileId, SecurityOption } from './types'

export const profiles: Record<ProfileId, ProfileConfig> = {
  EMPLOYED: {
    emoji: '👔',
    name: 'Empleado Formal',
    deposit: '2 meses',
    fields: [
      {
        id: 'cert_laboral',
        label: 'Certificado laboral (antigüedad, cargo, salario)',
        type: 'file',
        accept: '.pdf',
      },
      { id: 'colillas', label: '3 últimas colillas de pago', type: 'file', accept: '.pdf', multiple: true },
      {
        id: 'extractos',
        label: 'Extractos bancarios últimos 3 meses',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      { id: 'ref_personal_1', label: 'Referencia Personal 1 - Nombre', type: 'text' },
      { id: 'ref_personal_1_tel', label: 'Referencia Personal 1 - Teléfono', type: 'tel' },
      { id: 'ref_personal_2', label: 'Referencia Personal 2 - Nombre', type: 'text' },
      { id: 'ref_personal_2_tel', label: 'Referencia Personal 2 - Teléfono', type: 'tel' },
    ],
  },
  INDEPENDENT: {
    emoji: '💼',
    name: 'Independiente',
    deposit: '2 meses',
    fields: [
      { id: 'rut', label: 'RUT actualizado', type: 'file', accept: '.pdf' },
      {
        id: 'declaracion_renta',
        label: 'Declaración de renta últimos 2 años',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'extractos',
        label: 'Extractos bancarios últimos 6 meses',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'facturas',
        label: 'Facturas o contratos vigentes',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'camara_comercio',
        label: 'Certificado Cámara de Comercio (si aplica)',
        type: 'file',
        accept: '.pdf',
        required: false,
      },
    ],
  },
  RETIRED: {
    emoji: '😊',
    name: 'Pensionado',
    deposit: '2 meses',
    fields: [
      { id: 'cert_pension', label: 'Certificado de pensión actualizado', type: 'file', accept: '.pdf' },
      { id: 'resolucion', label: 'Resolución de pensión', type: 'file', accept: '.pdf' },
      {
        id: 'colillas_mesada',
        label: '3 últimas colillas de mesada',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'extractos',
        label: 'Extractos bancarios últimos 3 meses',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
    ],
  },
  ENTREPRENEUR: {
    emoji: '🏢',
    name: 'Empresario',
    deposit: '2 meses',
    fields: [
      {
        id: 'estados_financieros',
        label: 'Estados financieros (último año)',
        type: 'file',
        accept: '.pdf',
      },
      {
        id: 'camara_comercio',
        label: 'Certificado Cámara de Comercio vigente',
        type: 'file',
        accept: '.pdf',
      },
      {
        id: 'declaracion_renta',
        label: 'Declaración de renta últimos 2 años',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'extractos_empresariales',
        label: 'Extractos bancarios empresariales (6 meses)',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'extractos_personales',
        label: 'Extractos bancarios personales (6 meses)',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
    ],
  },
  INVESTOR: {
    emoji: '📈',
    name: 'Inversionista',
    deposit: '2 meses',
    fields: [
      {
        id: 'cert_cdts',
        label: 'Certificados de CDTs o inversiones',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'contratos_arriendo',
        label: 'Contratos de arriendo de otras propiedades',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'cert_rendimientos',
        label: 'Certificados de rendimientos financieros',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'extractos',
        label: 'Extractos bancarios últimos 3 meses',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
    ],
  },
  STUDENT: {
    emoji: '🎓',
    name: 'Estudiante',
    deposit: '3 meses',
    fields: [
      { id: 'cert_matricula', label: 'Certificado de matrícula vigente', type: 'file', accept: '.pdf' },
      {
        id: 'carta_patrocinador',
        label: 'Carta del patrocinador/padre autenticada',
        type: 'file',
        accept: '.pdf',
      },
      { id: 'nombre_patrocinador', label: 'Nombre completo del patrocinador', type: 'text' },
      { id: 'cedula_patrocinador', label: 'Cédula del patrocinador', type: 'text' },
      { id: 'tel_patrocinador', label: 'Teléfono del patrocinador', type: 'tel' },
    ],
  },
  FOREIGN: {
    emoji: '🌍',
    name: 'Extranjero Local',
    deposit: '3 meses',
    fields: [
      { id: 'pasaporte', label: 'Pasaporte', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'visa', label: 'Visa vigente', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'cedula_extranjeria', label: 'Cédula de extranjería', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'contrato_laboral', label: 'Contrato laboral en Colombia', type: 'file', accept: '.pdf' },
      {
        id: 'extractos',
        label: 'Extractos cuenta bancaria colombiana (3 meses)',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      { id: 'cert_laboral', label: 'Certificado laboral empresa colombiana', type: 'file', accept: '.pdf' },
    ],
  },
  NOMAD: {
    emoji: '🌐',
    name: 'Nómada Digital',
    deposit: '3-6 meses',
    fields: [
      { id: 'pasaporte', label: 'Pasaporte', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'visa', label: 'Visa (si aplica)', type: 'file', accept: '.pdf,.jpg,.png', required: false },
      {
        id: 'contratos',
        label: 'Contratos laborales apostillados',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'extractos_internacionales',
        label: 'Extractos cuenta internacional (6 meses)',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'comprobantes_ingresos',
        label: 'Comprobantes de ingresos en USD/EUR',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
    ],
  },
  UNEMPLOYED: {
    emoji: '🧾',
    name: 'Desempleado',
    deposit: '2 meses',
    fields: [
      { id: 'ref_personal_1', label: 'Referencia Personal 1 - Nombre', type: 'text' },
      { id: 'ref_personal_1_tel', label: 'Referencia Personal 1 - Teléfono', type: 'tel' },
      { id: 'ref_personal_2', label: 'Referencia Personal 2 - Nombre', type: 'text' },
      { id: 'ref_personal_2_tel', label: 'Referencia Personal 2 - Teléfono', type: 'tel' },
      { id: 'extractos', label: 'Extractos bancarios últimos 3 meses', type: 'file', accept: '.pdf', multiple: true },
    ],
  },
}

export const securityOptions: SecurityOption[] = [
  {
    id: 'double',
    name: 'Doble Garantía Personal',
    description: 'Dos Codeudores',
    requirements: 'Ingresos combinados ≥ 3x canon',
    fields: [
      { id: 'cedula_codeudor_1', label: 'Cédula Codeudor 1', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'cedula_codeudor_2', label: 'Cédula Codeudor 2', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'cert_laboral_1', label: 'Certificado laboral Codeudor 1', type: 'file', accept: '.pdf' },
      { id: 'cert_laboral_2', label: 'Certificado laboral Codeudor 2', type: 'file', accept: '.pdf' },
      {
        id: 'declaracion_renta_1',
        label: 'Declaración de renta o extractos Codeudor 1',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'declaracion_renta_2',
        label: 'Declaración de renta o extractos Codeudor 2',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'cert_tradicion_1',
        label: 'Certificado de tradición Codeudor 1 (si aplica)',
        type: 'file',
        accept: '.pdf',
        required: false,
      },
      {
        id: 'cert_tradicion_2',
        label: 'Certificado de tradición Codeudor 2 (si aplica)',
        type: 'file',
        accept: '.pdf',
        required: false,
      },
      {
        id: 'carta_aceptacion_1',
        label: 'Carta de aceptación firmada Codeudor 1',
        type: 'file',
        accept: '.pdf',
      },
      {
        id: 'carta_aceptacion_2',
        label: 'Carta de aceptación firmada Codeudor 2',
        type: 'file',
        accept: '.pdf',
      },
    ],
  },
  {
    id: 'reinforced',
    name: 'Garantía Personal Reforzada',
    description: 'Un Codeudor con Mayor Capacidad',
    requirements: 'Ingresos del codeudor ≥ 4x canon',
    fields: [
      { id: 'cedula_codeudor', label: 'Cédula del codeudor', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'cert_laboral', label: 'Certificado laboral', type: 'file', accept: '.pdf' },
      {
        id: 'declaracion_renta',
        label: 'Declaración de renta o extractos',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'cert_tradicion',
        label: 'Certificado de tradición (preferible)',
        type: 'file',
        accept: '.pdf',
        required: false,
      },
      { id: 'carta_aceptacion', label: 'Carta de aceptación firmada', type: 'file', accept: '.pdf' },
    ],
  },
  {
    id: 'insurance',
    name: 'Garantía con Aseguradora',
    description: 'Póliza de Arrendamiento',
    requirements: 'Score crediticio + Ingresos ≥ 3x canon',
    fields: [
      {
        id: 'solicitud_poliza',
        label: 'Solicitud de póliza (formato aseguradora)',
        type: 'file',
        accept: '.pdf',
      },
      { id: 'autorizacion_credito', label: 'Autorización estudio de crédito', type: 'checkbox' },
      { id: 'cert_ingresos', label: 'Certificado de ingresos validado', type: 'file', accept: '.pdf' },
      { id: 'poliza_pagada', label: 'Comprobante de pago de póliza', type: 'file', accept: '.pdf' },
    ],
  },
  {
    id: 'mixed',
    name: 'Garantía Mixta Premium',
    description: 'Codeudor + Póliza',
    requirements: 'Codeudor con capacidad + Score crediticio',
    fields: [
      { id: 'cedula_codeudor', label: 'Cédula del codeudor', type: 'file', accept: '.pdf,.jpg,.png' },
      { id: 'cert_laboral', label: 'Certificado laboral del codeudor', type: 'file', accept: '.pdf' },
      {
        id: 'declaracion_renta',
        label: 'Declaración de renta o extractos del codeudor',
        type: 'file',
        accept: '.pdf',
        multiple: true,
      },
      {
        id: 'cert_tradicion',
        label: 'Certificado de tradición (preferible)',
        type: 'file',
        accept: '.pdf',
        required: false,
      },
      {
        id: 'carta_aceptacion',
        label: 'Carta de aceptación firmada del codeudor',
        type: 'file',
        accept: '.pdf',
      },
      {
        id: 'solicitud_poliza',
        label: 'Solicitud de póliza (formato aseguradora)',
        type: 'file',
        accept: '.pdf',
      },
      { id: 'autorizacion_credito', label: 'Autorización estudio de crédito', type: 'checkbox' },
      { id: 'cert_ingresos', label: 'Certificado de ingresos validado', type: 'file', accept: '.pdf' },
      { id: 'poliza_pagada', label: 'Comprobante de pago de póliza', type: 'file', accept: '.pdf' },
    ],
  },
]
